spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb
#    username: embarkx
#    password: embarkx
#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create


#server:
#  port: 8082


